### PR TITLE
Google fonts updated.

### PR DESCRIPTION
**Pull request by Ryu-k**
Updated Google Fonts List.

### CODE REVIEW

**Comment by nikitahl** [comment]
> Updated Google Fonts List.

Hi Lucas!

Can you please specify which fonts have been added, so it's easier and faster for us to check and compare to the previous version?

Thank you.

**Comment by Ryu-k** [comment]
Hi, I used google api to get all the google fonts currently available to add update the fonts that were missing, so to be honest, I can't tell you exactly which one has been added.
I should have adjusted the spacing to match your patern exactly so it would have be easier to compare the files though.

**Comment by nikitahl** [comment]
I see. 
Can you please update the minified file, so it doesn't have spaces? It affects the file size, thus the plugin zip size as well.
Also, we need to sync your changes to the Font Managed addon. After we ensure that everything's working we will merge PR.

**Comment by Ryu-k** [comment]
Hi, I minified the file, and regarding tools/google-fonts/webfonts.json, I kept the exact same format you are using.

**Comment by nikitahl** [comment]
Hello!

We've made a separate PR for Google fonts, as additional changes were required, like updating an image with fonts for TinyMCE.

https://github.com/VisualComposer/builder/pull/2488

**Pull request closed without merging**
